### ISSUE TITLE
Filemanager only works with Tinymce editor

### ISSUE THREAD

**Issue by wvdweerd** [BlogEngine/BlogEngine.NET#111]
I tried the latest version, just to see what has changed since version 3.1.
And I noticed that the filemanager only works when using Tinymce as editor.

I assume this is caused by the direct reference to tinymce in the fileManagerController.js:
`var wm = top.tinymce.activeEditor.windowManager;`

Is the support for bootstrap and summernote being dropped?

Regards,
Wouter

**Comment by jradxl** [comment]
I too have noticed that the FileManager menu item is no longer present in the out-of-the box 3.3.5.0

The Key referred to in http://dnbe.net/docs/post/multiple-post-editors is not present

And adding the Key, causes BlogEngine to break
<add key="BlogEngine.DefaultEditor" value="~/editors/summernote/editor.cshtml" />

so I guess it's not
