### ISSUE TITLE
Recaptcha will not work if it fails a single time

### ISSUE THREAD

**Issue by jpakin** [BlogEngine/BlogEngine.NET#112]
Recaptcha works if successful, but if a user fails the recaptcha and attempts again, even if they enter the correct phrase the form will not submit.

This is from a new installation of 3.3.

I get an unreachable code error in Fx
![unreachablecode](https://cloud.githubusercontent.com/assets/1186592/19214728/36f9d608-8d58-11e6-91e1-f2e8d24e18a6.PNG)

**Comment by jradxl** [comment]
I've found this too in the site's Contact form. If the User fails the Recaptcha the words are refreshed, no indication message is shown to user that it has failed, and the icon over the Send button remains as no-entry. It's necessary for user to leave page (select Home, for example) and start again with data entry/
