### ISSUE TITLE
Backup features missing

### ISSUE THREAD

**Issue by scrummie02** [BlogEngine/BlogEngine.NET#115]
I have the latest code installed with a SQL database.  I"m trying to transfer and there is no way to back up the blog in blog.ml format.

**Comment by sqc1999** [comment]
In admin->settings->advanced，there is button that allows you to back up your posts in BlogML.

**Comment by scrummie02** [comment]
I don't see an advanced tab

**Comment by scrummie02** [comment]
Using 3.2.0.3 trying to backup and upgrade to latest version.

**Comment by sqc1999** [comment]
Oh, sorry for my mistake.
The `Advanced` tab is disabled if the `BlogEngine.UsageScenario` setting in `Web.config` is set to `singleblog`.
Before the project maintainer fix the problem, there are two ways to get into the advanced settings page:
- Change the code in https://github.com/rxtur/BlogEngine.NET/blob/master/BlogEngine/BlogEngine.NET/admin/themes/standard/sidebar.cshtml#L90 to make the `Advanced` visible.
- Type `http(s)://yoursite/admin/#/settings/advanced` in the address bar of your browser and press enter (`yoursite` is the domain name of your blog).

**Comment by sqc1999** [comment]
@rxtur Could you please take a look at this? Is it just a bug, or there is some reason for this?

**Comment by scrummie02** [comment]
Your solutions seem to work...now I can import my stuff over to the new site.  Thanks.
