### ISSUE TITLE
Published blog post is not visible if not logged in

### ISSUE THREAD

**Issue by sai-manoj-kumar** [BlogEngine/BlogEngine.NET#117]
@rxtur : I have recently setup a blog in azure web apps from the marketplace. I have created a new blog post and it is not visible if I log out. I am sure that I have published the post. I am using SimpleBlog Theme. I have enabled Disqus comments. I tried moving back to BlogEngine comments and the problem still persists. I have upgraded to the latest version, using the update feature in the dashboard after login.

**Comment by ysaimanojkumar** [comment]
Forgot to mention, that I have upgraded to the latest version, using the update feature in the dashboard after login.

**Comment by sqc1999** [comment]
Maybe a working example is needed?

**Comment by ysaimanojkumar** [comment]
@sqc1999 You mean, repro of the issue? http://blog.ysaimanojkumar.com/ Check this link. I have published a test post. Tell me if you can see it or not.

**Comment by ysaimanojkumar** [comment]
Not sure if this helps but I see these errors in the Developer console in my firefox:

> "NetworkError: 404 Not Found - http://blog.ysaimanojkumar.com/editors/tiny_mce_3_5_8/plugins/syntaxhighlighter/styles/shCore.css"
> shCore.css
> "NetworkError: 404 Not Found - http://blog.ysaimanojkumar.com/editors/tiny_mce_3_5_8/plugins/syntaxhighlighter/styles/shThemeDefault.css"
> shTheme...ult.css
> "NetworkError: 404 Not Found - http://blog.ysaimanojkumar.com/editors/tiny_mce_3_5_8/plugins/syntaxhighlighter/scripts/XRegExp.js"
> XRegExp.js
> "NetworkError: 404 Not Found - http://blog.ysaimanojkumar.com/editors/tiny_mce_3_5_8/plugins/syntaxhighlighter/scripts/shCore.js"
> shCore.js
> "NetworkError: 404 Not Found - http://blog.ysaimanojkumar.com/editors/tiny_mce_3_5_8/plugins/syntaxhighlighter/scripts/shAutoloader.js"
> shAutoloader.js
> "NetworkError: 404 Not Found - http://blog.ysaimanojkumar.com/editors/tiny_mce_3_5_8/plugins/syntaxhighlighter/shActivator.js"
> shActivator.js
> "NetworkError: 404 Not Found - http://blog.ysaimanojkumar.com/editors/tiny_mce_3_5_8/plugins/syntaxhighlighter/scripts/XRegExp.js"
> XRegExp.js
> "NetworkError: 404 Not Found - http://blog.ysaimanojkumar.com/editors/tiny_mce_3_5_8/plugins/syntaxhighlighter/scripts/shCore.js"
> shCore.js
> "NetworkError: 404 Not Found - http://blog.ysaimanojkumar.com/editors/tiny_mce_3_5_8/plugins/syntaxhighlighter/scripts/shAutoloader.js"

Is there any way to see some logs on the server?

**Comment by sqc1999** [comment]
It seems that it's hard to figure out what's wrong with the information I have currently.
Could you please do the following things to help me debug on this issue?
- Change your admin password to `123456` (or something similar and tell me about that).
- Dump your database to a `.sql` file.
- Change back your password to the original one.
- Give me the database dump file, contents under the `App_Data` directory, the `Web.config` file.
- Tell me if there is anything changed on the source code.
Then I can try to reproduce the issue in my environment.

**Comment by ysaimanojkumar** [comment]
@sqc1999 Sorry for delayed reply. But I think I have figured out and why it is happening. My timezone is UTC +5:30 which I haven't configured in the settings and by default it seems to be set to UTC. So, the post is not visible when not logged-in, until 5:30 hours from being published.

**Comment by ysaimanojkumar** [comment]
I am not sure if this is a bug. I think at least it should be communicated to the user that settin the correct timezone is very important.

**Comment by sqc1999** [comment]
I'm glad to hear that.
I used to face problems about timezone, too. But if didn't misunderstood, the maintainer thinks that it's the expected behavior.

**Comment by kamil-mrzyglod** [comment]
This is exactly what I investigated some time ago -> https://github.com/rxtur/BlogEngine.NET/issues/87
