### ISSUE TITLE
Title is not showing up on TextBox Widget in new standard theme

### ISSUE THREAD

**Issue by LoveCSharp** [BlogEngine/BlogEngine.NET#124]
I upgraded my blow from v1.5 to 3.5 and was checking standard theme. I noticed that textbox widget titles are not shown. There used to be a setting to show the title but the setting is not available any more. 

Can anyone tell me how to show titles in textbox widget?

**Comment by plykkegaard** [comment]
You need to mess around with code a little

New Razor code for the Textbox Widget

```
@using BlogEngine.NET.Custom.Widgets
@{
    var title = Model.Title;
    var settings = Common.GetSettings(Model.Id);
    var txt = "";
    if (settings != null && settings.Count > 0)
    {
        txt = HttpUtility.HtmlDecode(settings["content"]);
    }
}
<div class="Widget widget textbox">
    <h4 class="WidgetHeader widget-header">@title</h4>
    <div class="WidgetContent widget-content">
        @Html.Raw(txt)
    </div>
</div>
```
location in solution:
\BlogEngine.NET\Custom\Widgets\TextBox\widget.cshtml

Stylesheet for the Textbox (comment out background color and padding)

```
.textbox {
    /*background: $color-widget;

    padding: 1.5rem;*/

    p:last-child {
        margin-bottom: 0;
    }

    .no-border {
        border: none;
    }
}
```
location in solution:
\BlogEngine.NET\Custom\Themes\Standard\src\scss\widgets\_textbox.scss
