### ISSUE TITLE
blogengine tries to send email to multiple email addresses. Why?

### ISSUE THREAD

**Issue by watoo** [BlogEngine/BlogEngine.NET#130]
In the admin panel, I have configured my email address. Whenever I publish a post, my email tires to send email to following email addresses. 

**postmaster@hotmail.com
postmaster@hotmail.com
hslfzgn@outlook.com
karpfmm@outlook.com
zfhwnvq@outlook.com
xlpaqzh@outlook.com
wcgtodr@outlook.com
vbmlgtu@outlook.com
rxrvttx@outlook.com 
pajdgap@outlook.com
nfnsdkc@outlook.com
kvsscvz@outlook.com
djqsxis@outlook.com
azmpwrk@outlook.com
?hvuuqz@outlook.com
?fqtqki@outlook.com**

All emails have subject:
**Delivery Status Notification (Failure)**

Why it is so?

**Comment by sqc1999** [comment]
Take a look at the settings of your `Newsletter` widget. I think it is the only thing that may send emails when publishing posts.

**Comment by sqc1999** [comment]
The newsletter widget allows others to subscribe to your blog. Then whenever there are new posts, it will send emails to the subscribers' emails to notify them.

**Comment by almorax** [comment]
Fake e-mail addresses. That's why I removed Newsletter widget on my blog.

**Comment by watoo** [comment]
okay, how can I check the newsletter subscribers list?

**Comment by sqc1999** [comment]
Go to the widget settings page(https://www.sharpdoor.com/admin/#/custom/widgets). You can find a widget named `Newsletter`. The subscriber list is in its settings.

**Comment by prakash-manit** [comment]
Hello @watoo , May I know what details u filled to make mailing work?
