### ISSUE TITLE
BlogEngine 3.3.5+ on Linux and Mono

### ISSUE THREAD

**Issue by jradxl** [BlogEngine/BlogEngine.NET#138]
What is the current thoughts about BlogEngine.NET running on Linux (Ubuntu) under Mono.
That is both to Compile and Run!!
Is "fastcgi-mono-server", (ie Xsp4) likely to be able to run it?

For compling:
Trying, I see that System.Web.Entity and System.Web.Helpers are missing from
https://github.com/mono/mono/tree/master/mcs/class

So, we are a bit closer than @rxtur's comment on 18 Feb 2014!

I assume that BlogEngine.NET using ASP.NET Core is very unlikely? Yes/No?

Thx

**Comment by jradxl** [comment]
Wow! I do have it working on Mono and Ubuntu, using HyperFastCgi Server.
- been a bit of a trial understanding Mono, MonoDevelop and slighty modifying BlogEngine.NET to make it work. See http://radders.me

**Comment by EtaoinWu** [comment]
How do you make it? I tried mono but failed.
