### ISSUE TITLE
Plugins and Widgets galleries don't work 

### ISSUE THREAD

**Issue by ugochirico** [BlogEngine/BlogEngine.NET#144]
I have just upgraded my blog to the latest version 3.5.5.0.
When I go to the Plugins or to Widgets gallery by clicking "New" to add a new one, I don't see any plugin or widget.
I tried to select "Latest", "Most Downloaded" or "Highest Rated" but I don't see any item in the page.

How to fix that?

**Comment by goranhell** [comment]
The GalleryFeedRul shoud be set to 'http://dnbe.net/v01/nuget'. Check that you don't point elsewhere.

**Comment by ugochirico** [comment]
@goranhell where can I find GalleryFeedUrl?

**Comment by ugochirico** [comment]
If I type that url in the browse the xml I got doesn't have any item:
```
<service xmlns:atom="http://www.w3.org/2005/Atom" xmlns:app="http://www.w3.org/2007/app" xmlns="http://www.w3.org/2007/app" xml:base="http://dnbe.net/v01/nuget/">
<workspace>
<atom:title>Default</atom:title>
<collection href="Packages">
<atom:title>Packages</atom:title>
</collection>
</workspace>
</service>
```

**Comment by goranhell** [comment]
It's set in BlogConfig.cs by default but can be overwritten by a setting in Web.Config.

**Comment by ugochirico** [comment]
@goranhell ok, but the xml I found in the url you suggested doesn't contains any item. See my post above

**Comment by goranhell** [comment]
I don't know how that page works, but I suggest that you check that you don't point elsewhere.
Probably in Web.Config  - appsettings - key="BlogEngine.GalleryFeedUrl

**Comment by ugochirico** [comment]
@goranhell yes. I set BlogEngine.GalleryFeedUrl in the appsettings section in the web.config with 'http://dnbe.net/v01/nuget' but the gallery is still empty

**Comment by goranhell** [comment]
Then I don't know. It works for me

**Comment by rxtur** [comment]
You might need to check this out if you haven't:

In 3.3 most of the user controls were removed and all widgets replaced with Razor views. Because it was rewrite (almost) from scratch, some of the widgets were combined and others renamed for consistency. This makes new widgets incompatible with currently used. Auto update will completely remove custom/widgets folder and replace it with new. Then blogger can go to admin/custom/widgets and drag-and-drop desired widgets to the theme zones and customize them.

http://www.dotnetblogengine.net/post/blogengine-net-3-3-goes-live

**Comment by goranhell** [comment]
I thought the question was why no widgets was shown in the gallery.

**Comment by ugochirico** [comment]
@rxtur Many thanks. now the problem is clear.
Can you also give me some suggestions to the other issues I posted some days ago? I have my blog almost blocked

**Comment by jrblack10** [comment]
New install of 3.5.5, uploaded from back up App_Data\files\*.*, App_Data\pages\*.* and App_Data\posts\*.*.  Galleries for Themes, Plugins and Widgets do not work.  There is no appSettings for BlogEngine.GalleryFeedUrl.  But when I add (<add key="BlogEngine.GalleryFeedUrl" value"http://dnbe.net/v01/nuget" />), the blog no longer loads with this error:  
     500 - Internal server error.
     There is a problem with the resource you are looking for, and it cannot be displayed.
@ugochirico, did you get the Galleries working?

**Comment by ugochirico** [comment]
No, I was not able to make it working. BlogEngine seems abandoned :(

**Comment by canertosuner** [comment]
Is there any solution about it ? I am still having a problem about the all galleries widget, theme etc. an the main point is it works on locally. I mean the gallery page does not display anything while it’s working on the server, but it works on my local pc iis-host.

**Comment by kenllyacosta** [comment]
Hello, try to enable Read/Write permission to this folder on you server for all users.

Let us know anything.

**Comment by canertosuner** [comment]
@kenllyacosta it's already done, I attached a screenshot of the Add New Theme Gallery Page network result. It's empty

![image](https://user-images.githubusercontent.com/20043149/81041273-1d00b880-8eb6-11ea-9900-e08ed21b3127.png)
