### ISSUE TITLE
URL issue breaks admin dashboard normal load

### ISSUE THREAD

**Issue by command0r** [BlogEngine/BlogEngine.NET#145]
I've spotted a very weird error recently and I thought it was related to db and/or incorrect upgrade from the previous version. When entering the admin dashboard the network console in Chrome complaints, it cannot find the following resources:
Failed to load resource: the server responded with a status of 404 (Not Found)
Error: [$compile:tpload] errors.angularjs.org/1.3.0/$compile/tpload?p0=app%2Fdashboard%2FdashboardView.html
Please see screenshot attached to [imgbb ](url=https://ibb.co/kAdTWQ)service here.

Well, I found what was it... damn, I spend quite a lot of time figuring out what's wrong.
It turned out, steps to reproduce are simple. I was looking in the wrong place initially, blaming database...
1. Basically, if you not logged in and press 'admin' link, it opens login page and after entering credentials, it redirects you to straight to admin page, as usual. The link in this case would be __localhost/admin/#/__
2. If you're not logged in and say, you type localhost/admin in the url, it redirects you to straight to login page, as usual, but after successful login, the url would be **localhost/admin#/** and the dashboard won't show up. In this case you have to fix it manually or click on the other menu item and after returning to admin console it'll load normally. Under certain circumstances, the url isn't fixed by surfing the other menu items and in this case, once you click on the 'dashboard', it kicks you out to the login page.
Seems like URL rewrite issue.

**Comment by mainmind83** [comment]
@francisdotbio closing all issues?
