### ISSUE TITLE
Error When I deploy BlogEngine  To IIS

### ISSUE THREAD

**Issue by gbade** [BlogEngine/BlogEngine.NET#147]
I can run run BlogEngine on my local system. But when I try deploying to IIS, I get this errors of late,
Cannot insert the value NULL into column 'DataStoreSettingRowId', table 'BlogEngine.dbo.be_DataStoreSettings'; column does not allow nulls. INSERT fails.
The statement has been terminated.
`{
  var app = (HttpApplication)sender;
   BlogEngineConfig.Initialize(app.Context);
 }`

`Source File:  c:\inetpub\wwwroot\IdeasPortal\BlogEngine\BlogEngine.NET\Global.asax    Line:  8 
`
I have done a clean and build and deployed all to no avail.

I also tried viewing on Firefox, I get a different error - 

Cannot insert the value NULL into column 'UserID', table 'BlogEngine.dbo.be_Users'; column does not allow nulls. INSERT fails.
The statement has been terminated. 

Please help in resolving this.

**Comment by gbade** [comment]
I ran this on another web server. I got no errors. Turns out the server had issues plus VS 2013's build was not without errors. 

I am having other issues I'm dealing with - When i try making a post, I get an `Error making toast` toastr message. Whereas this same project works without any hindrance on my computer.

I narrowed the post action to postEditController.js, to the $scope.save() function but I'm not getting any stack trace whatsoever in Inspect Element.

Please help in resolving this.

**Comment by kbdavis07** [comment]
Make sure you have read/write permissions on all of your folders on your server.

Could be reason why it works locally, but not on your server.

Ask yourself?

What is different from my local development environment and the one on the live server?

If it works locally but not on server it points to a "server" error and not with your website itself.

**Comment by gbade** [comment]
Hi kbdavis07,

Each time I deploy on a remote server on IIS, I get Error 500 - Internal Server Error, anytime I try creating a new post. I have followed procedures on deploying BlogEngine on IIS, i have created the NETWORK SERVICE property and given it permissions in the App_Data folder. But I am still getting this error. On my local computer, it works perfectly.
 PS: I followed this deployment guide

Please help in resolving this.
