### ISSUE TITLE
Admin Dashboard takes 4-5 minutes to load, doesn't work on many browsers.

### ISSUE THREAD

**Issue by jhodges13** [BlogEngine/BlogEngine.NET#166]
I've been using .Net BlogEngine for 5+ years. I'm having problems with the Admin Dashboard after upgrading to version 3.3.5.0, using MSSQL as the DB.

When I first log into the admin area it takes 4-5 minutes for the page to load. Usually, while its loading, I get messages that the page is unresponsive but, if I am patient, it does finally load and offers no errors. Seems like the delay is just part of the slow nature of Angular JS but I thought I would throw this out there and see if anyone has suggestions. 

I've also noticed that you can't load the Admin section using Chrome or FireFox on a Samsung Galaxy Tablet. I think this is also related to incompatibilities with Angular JS. I wish it wasn't used in the Admin section of all places, messed it all up and made the code complicated and unstable to use.

**Comment by jhodges13** [comment]
After thinking about the issue, I removed the News and Theme Gallery from the main dashboard page. The admin section loads in about 30-45 seconds now. Not sure how it will do on the Galaxy tablet that my wife wants to manage the site with.

**Comment by roboffer** [comment]
I've noticed recently that the news attempts to load from http://dotnetblogengine.net/syndication.axd which seems to be completely down so we've removed the news (and the gallery) too.
