### ISSUE TITLE
Unable to load Admin Panel 

### ISSUE THREAD

**Issue by niranjankala** [BlogEngine/BlogEngine.NET#167]
I have updated to current higher version of BlogEngine and also migrated to another hosting provider. After setting permissions on the folders, I found that website is loading correctly but admin section is not loading.

![step1](https://user-images.githubusercontent.com/1167308/31524750-48b291d8-afd9-11e7-9760-9f265a9ec526.PNG)

If i click on any menu item on then left side then it shows error and URL is little strange. See below image for reference:
![step 2](https://user-images.githubusercontent.com/1167308/31524803-a1da98e6-afd9-11e7-92fa-aa37b8298bbe.PNG)

#166 -- This issue may be similar to this one but may be I have little different behavior.

**Comment by asozyurt** [comment]
Hi @niranjankala, 
I had the same issue tonight. When i clicked random another item on sidebar and click again to Dashboard, it has loaded.

**Comment by atrgmyth** [comment]
I have the exact issue that niranjankala describes.

**Comment by asozyurt** [comment]
hi @atrgmyth, after some failed trials i noticed that blog engine must be the top level site, not a subfolder.
For example; www.example.com/blogEngine/ doesn't work and throws your exception. If it is already top level, try clicking another item from dashboard menu and try again.

**Comment by kirtanshah11** [comment]
Any resolution found for this? 

I am still facing the issue.

**Comment by hugodahl** [comment]
I have no knowledge about the internals of BE.net, however, from the looks of @niranjankala's 404 screenshot, it would appear that there is some Angular/AngularJS binding which isn't happening or being done, since the URL requested has the Angular binding syntax of a value wrapped in double curly braces ("{{" and "}}").

On the page from which you clicked the admin section link, it would be worth checking, from the browser's developer tools, whether the `.js` file(s?) for Angular are loaded or if an error occurred (401, 404, other). The pattern of the path should be "`http://yoursite.tld/<blogRoot>/Scripts/angular*.min.js"

**Comment by hugodahl** [comment]
@asozyurt I saw your comment about BE.net needing to be at the domain's top level, and I've got mine running in a sub-directory, `/blog`. What does need to be configured for this to work however is that, in IIS, the directory in which BE.net is deployed must be configured as an application.

**Comment by empiricaledgedm** [comment]
@hugodahl Yes what I found out is if the URL is **domain.com/blog/admin/** then the page will load successfully. 

However, if the url is **domain.com/blog/admin** then the page won't load.

In the first case the browser looks for dashboard.cshtml in ../admin/app/dashboard/dashboard.cshtml. 
But for the second the path becomes ../app/dashboard/dashboard.cshtml. This will give 404.

**Comment by kirtanshah11** [comment]
@hugodahl Yes what I found out is if the URL is **domain.com/blog/admin/** then the page will load successfully. 

However, if the url is **domain.com/blog/admin** then the page won't load.

In the first case the browser looks for dashboard.cshtml in ../admin/app/dashboard/dashboard.cshtml. 
But for the second the path becomes ../app/dashboard/dashboard.cshtml. This will give 404.
