### ISSUE TITLE
No method for users to unsubscribe from newsletter

### ISSUE THREAD

**Issue by cdecinko** [BlogEngine/BlogEngine.NET#178]
Newsletter emails are supposed to provide a way for people to unsubscribe but no link is shown.

**Comment by Gaetan-dc** [comment]
I agree. Moreover there simply doesn't seem to be a way to unsubscribe from the administration interface, I have to go and manually edit the newsletter.xml file

**Comment by rishki123** [comment]
O wao its such an amazing picture.Its so cool graphic designing art which is quite spell bounding.It should be published on writing services [https://cerasis.com/2017/11/02/logistics-as-your-major/](https://cerasis.com/2017/11/02/logistics-as-your-major/) official site.I am interested to see some more posts like this.Thanks.

**Comment by GretchenSimon** [comment]
I noticed last week that I am sitting more than I should actually. It's abnormal to work more than 10 hours for [ultius](https://topamericanwriters.com/ultius-com-review/) and guys it's so fatal for life. Thanks for sharing this post.
