### ISSUE TITLE
Project's License

### ISSUE THREAD

**Issue by aldaircruz** [BlogEngine/BlogEngine.NET#180]
Hi, 
What is the project's license?

Thank you!

**Comment by sai-manoj-kumar** [comment]
@rxtur , Can you please update the Project's open source license?

**Comment by sai-manoj-kumar** [comment]
@francisdotbio, Hello, Can you please let us know the project's source code license?

**Comment by kbdavis07** [comment]
It is the Microsoft Reciprocal License (Ms-RL).

You can edit code as much as you like, if you sell, you have to include all of BE code as open source so people can view it, but the parts you edit or made custom can be closed source.

Still have to keep the BE link at the bottom I think?

BE is basically not being updated any more.

This is the most recent project that is replacing BE

https://github.com/blogifierdotnet/Blogifier

So might want to switch to that.

**Comment by sai-manoj-kumar** [comment]
@kbdavis07, Thanks a lot for the response. I have checked the repo you have referred to, and it is licensed under MIT License. Is that repo not a fork of this?

**Comment by kbdavis07** [comment]
Nope, completely different project as it is using Core with MVC, this is using asp.net with webforms.

**Comment by sai-manoj-kumar** [comment]
Okay. Thanks @kbdavis07.
