### ISSUE TITLE
BE  3.3.5.0 | Getting MOD Error while saving post/page from windows Server

### ISSUE THREAD

**Issue by balavanchi** [BlogEngine/BlogEngine.NET#182]
Hi,

Getting "403 ModSecurity Action" error while saving/creating new post/page in the server.

It is working fine in local.

Below are the settings
- XML Blog
- Server Permission Give for Folders as Read/Write for user (Process/IIS)
- Full Trust in config file.
![image](https://user-images.githubusercontent.com/4972776/39176006-542728ca-47c9-11e8-8194-0d9484816759.png)

**Comment by ifonya** [comment]
Have you know anything?
We have the same problem. How did you solve it?
