### ISSUE TITLE
Menu Users?

### ISSUE THREAD

**Issue by PeterGyger** [BlogEngine/BlogEngine.NET#184]
Hello 

First Installation. Login with admin / admin. In the BE Menu is no item "Users"
![be-users](https://user-images.githubusercontent.com/40018804/41193769-a50b338c-6c11-11e8-9082-8b1bf8d35d32.jpg)

And i not change the Language to german. I prefere english.

Solution? Hint?

Many thanks in advance
Peter

**Comment by AlbertaLee** [comment]
Great blog, you have posted amazing restaurants, music and the site is really eventful and full of entertainment, [https://www.thebestessayservice.com/termpaperwriting.html](https://www.thebestessayservice.com/termpaperwriting.html) provides best services, tanks for sharing with this.

**Comment by scrummie02** [comment]
Did you compile it in VS in German? That's probably why.
