### ISSUE TITLE
Recaptcha not displaying on Contact page

### ISSUE THREAD

**Issue by cdecinko** [BlogEngine/BlogEngine.NET#185]
BlogEngine is using ReCaptcha version 1.1 which Google no longer supports and has been shut down.  This is leaving my contact form exposed and hanging in the wind with no protection from spammers and bots.  Is there a way to upgrade to ReCaptcha 2?  Since the source code for codebehinds is not exposed, I am unable to make the change myself.

**Comment by mainmind83** [comment]
Same problem on last version available ( 3.3.8.0)

**Comment by hassanlahham** [comment]
@mainmind83 Hi is it working with you, I means,  is this good solution?

**Comment by mainmind83** [comment]
@hassanlahham After so many years, the solution was... [migrate BlogEngine to WP](https://www.mainmind.com/blog/migracion-de-blogengine-net-a-wordpress/) ;(
