### ISSUE TITLE
Where to Add Canonical link in head?

### ISSUE THREAD

**Issue by RandAlThor** [BlogEngine/BlogEngine.NET#192]
I believe I need to add the canonical link the header of my home page. Where would I add this? Within the theme? within the default.aspx? On every page?
Hope someone can help, cheers.

**Comment by healingwell** [comment]
This is very interesting, thanks for posting!  I implemented this on my blog.  However, I noticed one problem.  Google doesn't recognize category page canonical URLs.  Instead they all point to the root?  Do you know why?  Here's one example: https://www.healingwell.com/articles/category/Allergies  

When I run this through Google Search Console, it says the user canonical declared is actually https://www.healingwell.com/articles/

**Comment by healingwell** [comment]
This solution does not appear to fix categories and their canonical listings.

**Comment by Dr-Oli** [comment]
Healingwell, you have update in post: https://blog.replacemagic.com/post/blogengine-extension-for-canonical-tags as there was one step missing and that was: 

"Finally, when everything is in place go to: protected override void OnLoad(EventArgs e) in BlogBasePage.cs and add call to AddCanonical() which I did just after AddMetaContentType()."

After checking ReplaceMagic blog I see that there are canonical links.
