### ISSUE TITLE
Content not loading after deploying to Azure App Service

### ISSUE THREAD

**Issue by prakash-manit** [BlogEngine/BlogEngine.NET#193]
Hello,
App was working fine until I deployed it to Azure App Service. It seems the write permission issue in azure for folder App_Data and Custom. I tried below option suggested in net but it didn't work.
http://sedodream.com/2011/11/08/SettingFolderPermissionsOnWebPublish.aspx

Any other or better way to fix the issue?

**Comment by kbdavis07** [comment]
You might want to change it with PowerShell?

![image](https://user-images.githubusercontent.com/5434970/45937214-19901600-bf8c-11e8-8d99-1fa38fcd0264.png)

![image](https://user-images.githubusercontent.com/5434970/45937227-2f9dd680-bf8c-11e8-8a9d-96b5451e9a99.png)

![image](https://user-images.githubusercontent.com/5434970/45937234-43e1d380-bf8c-11e8-9aa1-f68adf61f6fa.png)

From there you have ability to use powershell on the server.

[https://blogs.msdn.microsoft.com/benjaminperkins/2017/05/17/set-or-change-an-azure-app-service-file-or-folder-permission/](https://blogs.msdn.microsoft.com/benjaminperkins/2017/05/17/set-or-change-an-azure-app-service-file-or-folder-permission/)

https://www.business.com/articles/powershell-manage-file-system-acl/

https://blogs.msdn.microsoft.com/johan/2008/10/01/powershell-editing-permissions-on-a-file-or-folder/

**Comment by kbdavis07** [comment]
https://channel9.msdn.com/Blogs/devfish/BlogEngineNET-Azure-based-Blog-Up-and-Running-in-Ten-Minutes

**Comment by kbdavis07** [comment]
https://azuremarketplace.microsoft.com/en-us/marketplace/apps/BlogEngineNET.BlogEngineNET?tab=Overview

**Comment by prakash-manit** [comment]
Thanks Brian for your reference of Azure marketplace app and it worked. Apparently giving permission through Power shell didn't work.
