### ISSUE TITLE
Advisory - BlogEngine - XXE (XML External Entity)

### ISSUE THREAD

**Issue by DanielBishtawi** [BlogEngine/BlogEngine.NET#198]
Hello,

While testing the Netsparker web application security scanner we identified a XXE (XML External Entity) vulnerability in BlogEngine. Can you please advise whom shall we contact to disclose the vulnerability details so it can be fixed?

Please email me at daniel@netsparker.com for the technical details.

Looking forward to hearing from you.

Regards,

Daniel Bishtawi
Marketing Administrator | Netsparker Web Application Security Scanner

**Comment by irbishop** [comment]
This may be fixed with #206
