### ISSUE TITLE
user manual

### ISSUE THREAD

**Issue by starg556** [BlogEngine/BlogEngine.NET#203]
Having difficulty learning basic processes in blogengine.  Can't seem to find much in the way of information on working within blogengine.  Such as a user manual.

**Comment by Farrell23** [comment]
@starg556 I was motivated by this project, so I'm working on a tutorial, but first in Russian)

**Comment by starg556** [comment]
@Farrell23  Thank you, I wait for your tutorial in English

**Comment by Farrell23** [comment]
@starg556 I will try as soon as possible, since I thought to describe the project first - https://github.com/blogifierdotnet/Blogifier

**Comment by figuerres** [comment]
@starg556 what kinds of things are you looking for ?

i am new to this software but i am a developer and have used a few other blogs in the past.

if you can ask a specific question i may be able to help.
