### ISSUE TITLE
Remove hashtag # from admin links

### ISSUE THREAD

**Issue by ingfada** [BlogEngine/BlogEngine.NET#204]
Hi,
how to remove "#" char from admin links?
For ex:

http://localhost:64079/admin/#/content/posts --> http://localhost:64079/admin/content/posts

Thanks
Ingd

**Comment by quell1** [comment]
Similar question to remove
http://localhost:64079/admin/posts/new-post-1
To
http://localhost:64079/admin/new-post-1

Also

http://localhost:64079/admin/page/newpage
To
http://localhost:64079/admin/newpage

**Comment by quell1** [comment]
After switching to dbprovider the url changes to http://localhost:64079/2019-12-1/new-post-1
