### ISSUE TITLE
after update to 3.3.8.0 missing Widget Zone (be_WIDGET_ZONE)

### ISSUE THREAD

**Issue by SandroRiz** [BlogEngine/BlogEngine.NET#219]
After update (that has deleted all my widgets in the custom/widgets folder) In the backoffice I don't have anymore the Widget Zone (be_WIDGET_ZONE) where to drag the widget that I want to render with the <blog:WidgetZone>control  (eg. the dashed rectangle)

![be](https://user-images.githubusercontent.com/7381657/68991628-e203bd80-0860-11ea-9a2c-fc7094ffbbda.png)

**Comment by kaciho** [comment]
Any guidance how to fix the bug? Or an update?
