### ISSUE TITLE
Recaptcha

### ISSUE THREAD

**Issue by mycanaletto** [BlogEngine/BlogEngine.NET#224]
Hi,

Recaptcha used via the plugin for the comments fail (404), any idea to solve this ?

Merci

![image](https://user-images.githubusercontent.com/45459269/79775488-9b951c00-8334-11ea-8322-328910e2205a.png)

**Comment by dansiegel** [comment]
I'm pretty sure the whole things needs to be updated since the recaptcha.net site no longer exists.
