### ISSUE TITLE
Unable to unpublish Posts

### ISSUE THREAD

**Issue by webzest** [BlogEngine/BlogEngine.NET#233]
Hi,
I have a blog with the following settings.  

![image](https://user-images.githubusercontent.com/6105504/95505260-10f4b780-097c-11eb-8b5e-b167a730f756.png)

I have a few questions that I need your assistance with resolving.  My first question is the following:
1.  What is the best platform or UI to use to edit the code for BlogEngine.Net?  I have Visual Studio 2019 and can edit and publish other .NET applications, but I am not sure how to edit and publish the BlogEngine.NET app to my production Server.  Right now, If I edit some back-end code, I have to copy the modified files to my production Server manually and Restart the App on the IIS Server.  It would be nice to use the Publish feature in VS2019, like I do with all the other Web apps that I develop.
2.  I am unable to Unpublish a Post.  Once I create it, the only way to hide it is to delete it.
3.  How do I create a New User account?

Thank you for your support and recommendations.

**Comment by farzindev** [comment]
1. You can publish BlogEngine with Visual Studio. and you can deploy it to your server. please Google it.
2. add write permissions to the App_Data and Custom folders on your server.
3. Take a look at https://blogengine.io/support/docs/configuration/


We are working on a new project similar to BlogEngine, please check it out:
https://github.com/blogifierdotnet/Blogifier
