### ISSUE TITLE
Upgrading Blog Engine version

### ISSUE THREAD

**Issue by jon241** [BlogEngine/BlogEngine.NET#234]
I've had an issue upgrading my version 3.1.1.0 to 3.3.80 where it would say I can upgrade but then say I've already upgraded on the next page. I worked around this issue in the Updater.asmx file by commenting out this line:

private static string _upgradeReleases = BlogConfig.GalleryFeedUrl.Replace("nuget", "/Releases/");

in favour of the line below it:

private static string _upgradeReleases = "http://dnbe.net/v01/Releases/";

But what I think was really wrong is this line is referencing BlogConfig for the Url and not BlogSettings.

**Comment by farzindev** [comment]
We are working on a new project similar to BlogEngine, please check it out:
https://github.com/blogifierdotnet/Blogifier
