### ISSUE TITLE
Predefine custom fields

### ISSUE THREAD

**Issue by blackbasket** [BlogEngine/BlogEngine.NET#235]
Hi,

is it possible to predefine some custom fields, so they can be filled in every new article?

Regards,
Marcel

**Comment by farzindev** [comment]
Yes there is:


```
// custom/themes/standard/PostView.ascx
<%
  var pass = "";
  if (Post.CustomFields != null && Post.CustomFields["pass"] != null)
  {
    pass = Post.CustomFields["pass"].Value;
  }
%>
<div>This is a custom post field: <%= pass %></div>
```


We are working on a new project similar to BlogEngine, please check it out:
https://github.com/blogifierdotnet/Blogifier
