### ISSUE TITLE
The WebResourceFilter breaks multi-byte characters.

### ISSUE THREAD

**Issue by sqc1999** [BlogEngine/BlogEngine.NET#91]
Every time the `Write()` method of the filter stream is called, the binary input is decoded using the UTF-8 encoding. But this may break some characters, because UTF-8 may use more than one bytes to represent a character, so a character may be split into two method calls.

**Comment by rxtur** [comment]
Need a test case: these are steps I do, this is what I get and this is what I expect.

**Comment by sqc1999** [comment]
Simply creating a post with non-ASCII characters(e.g. Chinese characters) will lead to this issue. But it  appear randomly because I can't control or predict the way the framework write to filter streams.
So I think a simple example will be much more helpful to explain the issue.
Assume that we're rendering a html page `<html>王宇鑫超强</html>`. And the UTF-8 encoded byte array of this string is "3C 68 74 6D 6C 3E **E7 8E 8B E5 AE 87 E9 91 AB E8 B6 85 E5 BC BA** 3C 2F 68 74 6D 6C 3E".
The first 6 bytes represents `<html>`, and the last 7 bytes represents `</html>`. Obviously each byte represents a character.
However, UTF-8 works differently for non-ASCII characters, see the bold part of the byte array, which represents `王宇鑫超强`, it uses two bytes to represent a character.
Let's assume that after some other process the framework started to write to an `WebResourceFilter` object.
If the framework sends the whole byte array to `WebResourceFilter.Write()`, everything works well. But there are no guarantee about this.
If the framework writes the whole html in two calls to `WebResourceFilter.Write()`. Assume the first time it sends the first 7 characters and the second time sends the rest. Note that the two bytes that represents `王` (`E7 8E`) are split.
Currently `WebResourceFilter.Write()` will decode the byte array as soon as it is called. So the first time it is called, the first 7 characters will be decoded to `<html>?`(the framework could not decode the standalone byte `E7`, so there is a question mark in the end of the string), the second call is similar. Finally the the framework calls `WebResourceFilter.Close()` and the object started to work using the incorrect string `<html>??宇鑫超强</html>`. The character `王` has been turned into two question marks!
I think this can be fixed by leave the bytes encoded in `WebResourceFilter.Write()` and store them in a `List<byte>` or something similar, and decode the whole byte array after `WebResourceFilter.Close()` is called.

**Comment by rxtur** [comment]
This all good, but if I can't reproduce the bug - how can I tell I fixed it? 
Last time I've seen this issue, I think, couple years ago...

**Comment by sqc1999** [comment]
Err... I am willing to find a way to reproduce the bug. but I have nothing on the computer that I am currently using except a web browser(No git, no Visual Studio, no IIS, etc).
I've already made the change I mentioned in the last paragraph of my previous comment, so I have to revert the change to reproduce the bug. This can't be done with computer I am using now... So I have to get started a few hours later.
In addition, even after I applied the changes to `WebResourceFilter` the issue still appears but much more rarely. In fact it is so rare that I can only see it on my production server but can't reproduce on my development PC.

**Comment by sqc1999** [comment]
@rxtur Finally I've got it done using notepad.exe...
Please see [https://stalker-blog.apphb.com/](https://stalker-blog.apphb.com/) and [https://stalker-blog.apphb.com/post/RSA-cryptography-system-and-transport-security-over-internet](https://stalker-blog.apphb.com/post/RSA-cryptography-system-and-transport-security-over-internet). The website is running my fork of BlogEngine.NET.
The problem appears:
![3](https://cloud.githubusercontent.com/assets/11770489/18373991/9afe1a18-767b-11e6-89ce-0486a7cbdf57.png)
![4](https://cloud.githubusercontent.com/assets/11770489/18373995/a2f6c0da-767b-11e6-8344-46594d8dd894.png)
To reproduce it, first check the "Compress WebResource.axd" checkbox in admin/#/settings/advanced, and create a long post that contains tons of non-ASCII characters. Then you will see some characters broken.

**Comment by rxtur** [comment]
Yes, this explains why I haven't seen this for a very long time - resource compression is off by default.
I can reproduce it now, thanks! I"m going to put it on hold though, will get to it later.

**Comment by doggy8088** [comment]
I can reproduce this problem as well.  After I remark `context.Response.Filter = new WebResourceFilter(context.Response.Filter);` line in the `CompressionModule.cs` file.  The problem is gone.

**Comment by doggy8088** [comment]
I leave my explaination on this issue in SO here: https://stackoverflow.com/questions/54644323/on-azure-web-app-service-sometime-get-character-65533-but-then-things-go-b/54644763#54644763

**Comment by doggy8088** [comment]
@rxtur You can check out Rick Strahl's post about [Capturing and Transforming ASP.NET Output with Response.Filter](https://weblog.west-wind.com/posts/2009/Nov/13/Capturing-and-Transforming-ASPNET-Output-with-ResponseFilter).  This implemented the right way to handle Response Filter Stream that need to get whole buffer to do the replacements but chunked buffer.

**Comment by doggy8088** [comment]
@francisdotbio Hi, is this issue been solved?
